trigger:
- master

pool:
 vmImage: 'ubuntu-latest'

# Pipeline > Stages > Jobs > Task (steps)

stages:
- stage: Build
  jobs: 
  - job: BuildImageDocker
    steps:
    - bash: echo BuildImageDocker
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.DefaultWorkingDirectory)'
        Contents: |
         **/*.yaml
         **/*.tf
        TargetFolder: '$(Build.DefaultWorkingDirectory)/configuration'