trigger:
- master

pool:
 vmImage: 'ubuntu-latest'

# Pipeline > Stages > Jobs > Task (steps)

stages:
- stage: Build
  jobs: 
  - job: BuildImageDocker
    steps:
    - bash: echo BuildImageDocker
  - job: PushImageDocker
    steps:
    - bash: echo Build SecondJob

- stage: DevDeploy
  dependsOn: Build
  jobs: 
  - job: DevDeploy
    steps:
    - bash: echo Build FirstJob

- stage: TestDeploy
  dependsOn: DevDeploy
  jobs: 
  - job: TestDeploy
    steps:
    - bash: echo Deploy Homologacao