trigger:
- master

pool:
 vmImage: 'ubuntu-latest'

# Pipeline > Stages > Jobs > Task (steps)

stages:
- stage: Build
  jobs: 
  - job: BuildImageDocker
    steps:
    - bash: echo BuildImageDocker
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
  - job: PushImageDocker
    steps:
    - bash: echo Build SecondJob

- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs: 
  - job: DevDeploy
    steps:
    - bash: echo $(environment)DeployJob

- stage: TestDeploy
  # condition: not[$(Build.SourceBranchName) == 'develop']
  variables:
    environment: QA
  dependsOn: DevDeploy
  jobs: 
  - job: TestDeploy
    steps:
    - bash: echo $(environment)DeployJob