trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(PipelineLevelVariable)
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - deployment: DevDeployJob
    environment: Dev
  - job: DevDeployJob11
    steps:
    - bash: echo DeployJob

- stage: ProdDeploy
  dependsOn: 
  - Build
  - DevDeploy
  jobs:
  - deployment: ProdDeployJob
    environment: Prod
  - job: ProdDeployJob
    steps:
    - bash: echo DeployJob