trigger:
- master

pool:
 vmImage: 'ubuntu-latest'

# Pipeline > Stages > Jobs > Task (steps)

variables:
  tag: '$(Build.BuildId)'
stages:
- stage: Build
  jobs: 
  - job: BuildImageDocker
    steps:
    - bash: echo BuildImageDocker
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)

    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'brunopraciano/curso-agu'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'