trigger:
- master

pool:
 vmImage: 'ubuntu-latest'

# Pipeline > Stages > Jobs > Task (steps)
jobs:
- job: Job1
  steps:
  - script: echo Job1
    displayName: 'Executar script de linha unica'
  - script: |
      echo Login realizado
      echo DB salvo com sucesso
    displayName: 'Autenticacao'
- job: Job2
  steps: 
  - script: echo Run Job2
    displayName: 'Job2'
